version: '3'
services:
  myapp-main:
    image: sdat_qap2_tournaments:latest
    ports:
      - 8080:8080
    environment:
    # - spring.datasource.url=jdbc:mysql://database-2.coqc1sowfzyu.ca-central-1.rds.amazonaws.com:3306/winter_2022
      - spring.datasource.url=jdbc:mysql://sdat-qap2.c8jy55e54air.us-east-1.rds.amazonaws.com:3306/sdat_qap2
      - spring.datasource.password=password
      - spring.datasource.username=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver